language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t musibs/docker-react-app -f Dockerfile.dev .

script:
    docker run -e CI=true musibs/docker-react-app npm run test -- --coverage



